apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: product-service:v1
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_DSN
              value: "$(DB_USER):$(DB_PASSWORD)@tcp(mysql:3306)/product_db?parseTime=true"
